### PR TITLE
Update footer.md

### PR DESCRIPTION
**Pull request by davidewarren**
Add suggest and edit button

### CODE REVIEW

**Comment by wslack** [comment]
doesn't look like the link works on the preview?

**Comment by davidewarren** [comment]
No it did not work

**Comment by davidewarren** [comment]
It works now but links to index.html, which is not a markdown file. 

I think it makes the most sense to link it to edit the report.md file, since that file has the majority of the content in md on the main page. Because it's a single page template I don't think we have to be concerned with ensuring the file path works for additional pages

**Comment by davidewarren** [comment]
Now it links to report.md

**Review by wslack — APPROVED** [review]

**Pull request merged**
