### PR TITLE
Federalist Pop-up

### PR DESCRIPTION
**Pull request by jeremyzilar**
## what we made better

We added a standard pop-up to Federalist sites!

This popup works by setting a cookie on the site for 60mins. After 60mins, the cookie invalidates. The next time the person comes back to the site, they see the pop-up again.

**Options**
- "preview" — will show the pop-up ONLY on Federalist Previews
- "work-in-progress" — will show the pop-up on all branches and views of the site.
- "password" — will add a password field to the pop-up
  - has the options to set the (soft) password in the config

The goal was to make it as easy as possible to configure in a site.
All JS/CSS/HTML is in the `popup.html` include.

### CODE REVIEW

**Comment by wslack** [comment]
Create multiple test branches please - with different features turned on - but only after first version of code is approved!

**Comment by jeremyzilar** [comment]
@thisisdano recommends that we remove the password option, and I agree.
It is not really a password and sets might set the wrong expectation with clients or people who use Federalist. 

It is best to be clear that this is open, and not a something that can be password protected.

**Comment by jeremyzilar** [comment]
**Preview:** https://federalist-proxy.app.cloud.gov/preview/18f/federalist-landing-page-template/preview-pop-up/

image

_To view, either clear your `work-in-progress` cookie 🍪 OR view it in an incognito window._

**Comment by wslack** [comment]
@jeremyzilar I agree with that but the option just makes its clear that its not "done" yet. I 100% think we should keep it for the sake of psychological safety. Maybe the popup should be called "speedbump" instead and have text that says "enter a password to interact with this public content."

**Comment by jeremyzilar** [comment]
I can make a quick mockup of this so that we can expand the discussion with others

**Comment by wslack** [comment]
(Update: Jeremy will do this)

**Pull request closed without merging**
